"""add_withdrawal_failure_fields_and_constraints

Revision ID: 746b04caca0c
Revises: 887ea8778d60
Create Date: 2026-01-06 21:04:20.861355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '746b04caca0c'
down_revision = '887ea8778d60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add withdrawal failure fields
    op.add_column('withdrawal_intents', sa.Column('failed_at', sa.DateTime(), nullable=True))
    op.add_column('withdrawal_intents', sa.Column('failure_reason', sa.Text(), nullable=True))
    
    # Update indexes
    op.drop_index('idx_withdrawal_status', table_name='withdrawal_intents')
    op.create_index('idx_withdrawal_status_created', 'withdrawal_intents', ['status', 'created_at'], unique=False)
    
    # Add unique constraint on (network, tx_hash) where tx_hash is not null to prevent double sending
    op.create_index(
        'idx_withdrawal_network_tx_hash_unique',
        'withdrawal_intents',
        ['network', 'tx_hash'],
        unique=True,
        postgresql_where=sa.text('tx_hash IS NOT NULL')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_withdrawal_network_tx_hash_unique', table_name='withdrawal_intents')
    op.drop_index('idx_withdrawal_status_created', table_name='withdrawal_intents')
    op.create_index('idx_withdrawal_status', 'withdrawal_intents', ['status'], unique=False)
    op.drop_column('withdrawal_intents', 'failure_reason')
    op.drop_column('withdrawal_intents', 'failed_at')
    # ### end Alembic commands ###
