"""add_deposit_intent_lifecycle_fields_and_constraints

Revision ID: 887ea8778d60
Revises: b59a7b46e2df
Create Date: 2025-12-23 05:49:40.103830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '887ea8778d60'
down_revision = 'b59a7b46e2df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposit_intents', sa.Column('amount_crypto', sa.Numeric(precision=20, scale=8), nullable=True))
    op.add_column('deposit_intents', sa.Column('detected_at', sa.DateTime(), nullable=True))
    op.add_column('deposit_intents', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    op.drop_index('idx_deposit_expires_at', table_name='deposit_intents')
    op.create_index('idx_deposit_address', 'deposit_intents', ['generated_address'], unique=False)
    op.create_index('idx_deposit_status_expires', 'deposit_intents', ['status', 'expires_at'], unique=False)
    
    # Create unique partial index on (network, tx_hash) where tx_hash is not null
    # This prevents double credit even if two workers process the same tx_hash concurrently
    op.execute("""
        CREATE UNIQUE INDEX idx_deposit_network_tx_hash_unique 
        ON deposit_intents (network, tx_hash) 
        WHERE tx_hash IS NOT NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_deposit_network_tx_hash_unique', table_name='deposit_intents')
    op.drop_index('idx_deposit_status_expires', table_name='deposit_intents')
    op.drop_index('idx_deposit_address', table_name='deposit_intents')
    op.create_index('idx_deposit_expires_at', 'deposit_intents', ['expires_at'], unique=False)
    op.drop_column('deposit_intents', 'confirmed_at')
    op.drop_column('deposit_intents', 'detected_at')
    op.drop_column('deposit_intents', 'amount_crypto')
    # ### end Alembic commands ###
