"""add_deposit_intent_lifecycle_fields_and_constraints

Revision ID: 887ea8778d60
Revises: b59a7b46e2df
Create Date: 2025-12-23 05:49:40.103830

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '887ea8778d60'
down_revision = 'b59a7b46e2df'
branch_labels = None
depends_on = None


def column_exists(table_name, column_name):
    """Check if a column exists in a table"""
    try:
        bind = op.get_bind()
        inspector = inspect(bind)
        columns = [col['name'] for col in inspector.get_columns(table_name)]
        return column_name in columns
    except Exception:
        return False


def index_exists(table_name, index_name):
    """Check if an index exists"""
    try:
        bind = op.get_bind()
        inspector = inspect(bind)
        indexes = [idx['name'] for idx in inspector.get_indexes(table_name)]
        return index_name in indexes
    except Exception:
        return False


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns only if they don't exist (for fresh databases, they may already exist)
    if not column_exists('deposit_intents', 'amount_crypto'):
        op.add_column('deposit_intents', sa.Column('amount_crypto', sa.Numeric(precision=20, scale=8), nullable=True))
    if not column_exists('deposit_intents', 'detected_at'):
        op.add_column('deposit_intents', sa.Column('detected_at', sa.DateTime(), nullable=True))
    if not column_exists('deposit_intents', 'confirmed_at'):
        op.add_column('deposit_intents', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    
    # Drop index only if it exists
    if index_exists('deposit_intents', 'idx_deposit_expires_at'):
        try:
            op.drop_index('idx_deposit_expires_at', table_name='deposit_intents')
        except Exception:
            pass
    
    # Create indexes only if they don't exist
    if not index_exists('deposit_intents', 'idx_deposit_address'):
        try:
            op.create_index('idx_deposit_address', 'deposit_intents', ['generated_address'], unique=False)
        except Exception:
            pass
    if not index_exists('deposit_intents', 'idx_deposit_status_expires'):
        try:
            op.create_index('idx_deposit_status_expires', 'deposit_intents', ['status', 'expires_at'], unique=False)
        except Exception:
            pass
    
    # Create unique partial index on (network, tx_hash) where tx_hash is not null
    # This prevents double credit even if two workers process the same tx_hash concurrently
    if not index_exists('deposit_intents', 'idx_deposit_network_tx_hash_unique'):
        try:
            op.execute("""
                CREATE UNIQUE INDEX IF NOT EXISTS idx_deposit_network_tx_hash_unique 
                ON deposit_intents (network, tx_hash) 
                WHERE tx_hash IS NOT NULL
            """)
        except Exception:
            pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_deposit_network_tx_hash_unique', table_name='deposit_intents')
    op.drop_index('idx_deposit_status_expires', table_name='deposit_intents')
    op.drop_index('idx_deposit_address', table_name='deposit_intents')
    op.create_index('idx_deposit_expires_at', 'deposit_intents', ['expires_at'], unique=False)
    op.drop_column('deposit_intents', 'confirmed_at')
    op.drop_column('deposit_intents', 'detected_at')
    op.drop_column('deposit_intents', 'amount_crypto')
    # ### end Alembic commands ###
