"""add_system_monitoring_models_alerts_heartbeats_reconciliation

Revision ID: 9fe7ab167cbe
Revises: 9b0990e66fba
Create Date: 2026-01-20 23:43:30.887675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fe7ab167cbe'
down_revision = '9b0990e66fba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # System Alerts table
    op.create_table('system_alerts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('type', sa.String(length=50), nullable=False),
        sa.Column('severity', sa.String(length=20), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('context', sa.JSON(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('dedupe_key', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
        sa.Column('resolved_at', sa.DateTime(), nullable=True),
        sa.Column('acknowledged_by', sa.Integer(), nullable=True),
        sa.Column('resolved_by', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    # System Heartbeats table
    op.create_table('system_heartbeats',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('service_name', sa.String(length=100), nullable=False),
        sa.Column('last_heartbeat_at', sa.DateTime(), nullable=False),
        sa.Column('meta', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('service_name')
    )

    # Reconciliation Reports table
    op.create_table('reconciliation_reports',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('date', sa.DateTime(), nullable=False),
        sa.Column('asset', sa.String(length=10), nullable=False),
        sa.Column('network', sa.String(length=20), nullable=False),
        sa.Column('total_user_available', sa.JSON(), nullable=False),
        sa.Column('total_user_reserved', sa.JSON(), nullable=False),
        sa.Column('total_user_liability', sa.JSON(), nullable=False),
        sa.Column('platform_hot_wallet_balance', sa.JSON(), nullable=False),
        sa.Column('platform_cold_wallet_balance', sa.JSON(), nullable=True),
        sa.Column('platform_total_balance', sa.JSON(), nullable=False),
        sa.Column('delta', sa.JSON(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('details', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    # Indexes for performance
    op.create_index('idx_system_alerts_status_created', 'system_alerts', ['status', 'created_at'], unique=False)
    op.create_index('idx_system_alerts_type_severity', 'system_alerts', ['type', 'severity'], unique=False)
    op.create_index('idx_system_alerts_dedupe_open', 'system_alerts', ['dedupe_key', 'status'], unique=False)
    op.create_index('idx_system_heartbeats_last_heartbeat', 'system_heartbeats', ['last_heartbeat_at'], unique=False)
    op.create_index('idx_reconciliation_reports_date_asset', 'reconciliation_reports', ['date', 'asset'], unique=False)
    op.create_index('idx_reconciliation_reports_status', 'reconciliation_reports', ['status'], unique=False)

    # Additional indexes for foreign keys and lookups
    op.create_index('ix_system_alerts_dedupe_key', 'system_alerts', ['dedupe_key'], unique=False)
    op.create_index('ix_system_alerts_id', 'system_alerts', ['id'], unique=False)
    op.create_index('ix_system_heartbeats_id', 'system_heartbeats', ['id'], unique=False)
    op.create_index('ix_system_heartbeats_service_name', 'system_heartbeats', ['service_name'], unique=False)
    op.create_index('ix_reconciliation_reports_date', 'reconciliation_reports', ['date'], unique=False)
    op.create_index('ix_reconciliation_reports_id', 'reconciliation_reports', ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop additional indexes
    op.drop_index('ix_reconciliation_reports_id', table_name='reconciliation_reports')
    op.drop_index('ix_reconciliation_reports_date', table_name='reconciliation_reports')
    op.drop_index('ix_system_heartbeats_service_name', table_name='system_heartbeats')
    op.drop_index('ix_system_heartbeats_id', table_name='system_heartbeats')
    op.drop_index('ix_system_alerts_id', table_name='system_alerts')
    op.drop_index('ix_system_alerts_dedupe_key', table_name='system_alerts')

    # Drop performance indexes
    op.drop_index('idx_reconciliation_reports_status', table_name='reconciliation_reports')
    op.drop_index('idx_reconciliation_reports_date_asset', table_name='reconciliation_reports')
    op.drop_index('idx_system_heartbeats_last_heartbeat', table_name='system_heartbeats')
    op.drop_index('idx_system_alerts_dedupe_open', table_name='system_alerts')
    op.drop_index('idx_system_alerts_type_severity', table_name='system_alerts')
    op.drop_index('idx_system_alerts_status_created', table_name='system_alerts')

    # Drop tables
    op.drop_table('reconciliation_reports')
    op.drop_table('system_heartbeats')
    op.drop_table('system_alerts')

    # ### end Alembic commands ###
