"""Add withdrawal and limit models

Revision ID: b0fa1d8d6ada
Revises: 
Create Date: 2025-12-10 18:18:37.386421

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect


def table_exists(table_name):
    """Check if a table exists in the database"""
    bind = op.get_bind()
    inspector = inspect(bind)
    return table_name in inspector.get_table_names()

# revision identifiers, used by Alembic.
revision = 'b0fa1d8d6ada'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create users table first (required by foreign keys)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('google_id', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('funds_usd', sa.Numeric(precision=15, scale=2), nullable=False, server_default='0.00'),
    sa.Column('referral_code_used', sa.String(length=50), nullable=True),
    sa.Column('referred_by_affiliate_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_users_google_id', 'users', ['google_id'], unique=True)
    op.create_index('ix_users_referral_code_used', 'users', ['referral_code_used'], unique=False)
    op.create_index('ix_users_referred_by_affiliate_id', 'users', ['referred_by_affiliate_id'], unique=False)
    
    op.create_table('platform_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset', sa.String(length=10), nullable=False),
    sa.Column('network', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('balance', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('is_hot_wallet', sa.Boolean(), nullable=True),
    sa.Column('min_balance_threshold', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('max_balance_threshold', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_multisig', sa.Boolean(), nullable=True),
    sa.Column('required_signatures', sa.Integer(), nullable=True),
    sa.Column('total_signatures', sa.Integer(), nullable=True),
    sa.Column('wallet_name', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_balance_check', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_index('idx_wallet_asset_network', 'platform_wallets', ['asset', 'network'], unique=False)
    op.create_index('idx_wallet_hot_active', 'platform_wallets', ['is_hot_wallet', 'is_active'], unique=False)
    op.create_index(op.f('ix_platform_wallets_id'), 'platform_wallets', ['id'], unique=False)
    op.create_table('user_daily_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('deposits_count', sa.Integer(), nullable=True),
    sa.Column('deposits_amount_usd', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('withdrawals_count', sa.Integer(), nullable=True),
    sa.Column('withdrawals_amount_usd', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('bets_count', sa.Integer(), nullable=True),
    sa.Column('bets_amount_usd', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_date_limits', 'user_daily_limits', ['date'], unique=False)
    op.create_index('idx_user_date_limits', 'user_daily_limits', ['user_id', 'date'], unique=True)
    op.create_index(op.f('ix_user_daily_limits_id'), 'user_daily_limits', ['id'], unique=False)
    op.create_table('withdrawal_intents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset', sa.String(length=10), nullable=False),
    sa.Column('network', sa.String(length=20), nullable=False),
    sa.Column('amount_crypto', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('to_address', sa.String(length=100), nullable=False),
    sa.Column('memo', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('tx_hash', sa.String(length=100), nullable=True),
    sa.Column('confirmations', sa.Integer(), nullable=True),
    sa.Column('network_fee', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('platform_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('kyc_required', sa.Boolean(), nullable=True),
    sa.Column('kyc_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_withdrawal_created_at', 'withdrawal_intents', ['created_at'], unique=False)
    op.create_index('idx_withdrawal_status', 'withdrawal_intents', ['status'], unique=False)
    op.create_index('idx_withdrawal_tx_hash', 'withdrawal_intents', ['tx_hash'], unique=False)
    op.create_index('idx_withdrawal_user_status', 'withdrawal_intents', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_withdrawal_intents_id'), 'withdrawal_intents', ['id'], unique=False)
    
    # Drop captcha tables if they exist (legacy tables)
    if table_exists('captcha_responses'):
        op.drop_index('ix_captcha_responses_id', table_name='captcha_responses')
        op.drop_table('captcha_responses')
    if table_exists('captcha_challenges'):
        op.drop_index('ix_captcha_challenges_challenge_id', table_name='captcha_challenges')
        op.drop_index('ix_captcha_challenges_id', table_name='captcha_challenges')
        op.drop_table('captcha_challenges')
    
    # Modify betting_records if it exists
    if table_exists('betting_records'):
        try:
            op.drop_constraint('fk_betting_records_match_id', 'betting_records', type_='foreignkey')
        except Exception:
            pass  # Constraint might not exist
    
    # Modify crypto_transactions if it exists
    if table_exists('crypto_transactions'):
        op.add_column('crypto_transactions', sa.Column('withdrawal_intent_id', sa.Integer(), nullable=True))
        try:
            op.alter_column('crypto_transactions', 'deposit_intent_id',
                       existing_type=sa.INTEGER(),
                       nullable=True)
        except Exception:
            pass  # Column might already be nullable
        op.create_index('idx_crypto_tx_created_at', 'crypto_transactions', ['created_at'], unique=False)
        op.create_index('idx_crypto_tx_deposit_intent', 'crypto_transactions', ['deposit_intent_id'], unique=False)
        op.create_index('idx_crypto_tx_status', 'crypto_transactions', ['status'], unique=False)
        op.create_index('idx_crypto_tx_withdrawal_intent', 'crypto_transactions', ['withdrawal_intent_id'], unique=False)
        op.create_foreign_key(None, 'crypto_transactions', 'withdrawal_intents', ['withdrawal_intent_id'], ['id'])
    
    # Modify deposit_intents if it exists
    if table_exists('deposit_intents'):
        op.create_index('idx_deposit_expires_at', 'deposit_intents', ['expires_at'], unique=False)
        op.create_index('idx_deposit_tx_hash', 'deposit_intents', ['tx_hash'], unique=False)
        op.create_index('idx_deposit_user_status', 'deposit_intents', ['user_id', 'status'], unique=False)
        op.create_foreign_key(None, 'deposit_intents', 'users', ['user_id'], ['id'])
    
    # Modify odds if it exists
    if table_exists('odds'):
            op.add_column('odds', sa.Column('ai_true_odd_X', sa.Numeric(), nullable=True))
        op.add_column('odds', sa.Column('ai_true_odd_2', sa.Numeric(), nullable=True))
        op.add_column('odds', sa.Column('ai_prob_home', sa.Float(), nullable=True))
        op.add_column('odds', sa.Column('ai_prob_draw', sa.Float(), nullable=True))
        op.add_column('odds', sa.Column('ai_prob_away', sa.Float(), nullable=True))
        op.add_column('odds', sa.Column('ai_confidence_score', sa.Float(), nullable=True))
        op.add_column('odds', sa.Column('ai_model_version', sa.String(length=255), nullable=True))
        op.add_column('odds', sa.Column('ai_prediction_timestamp', sa.DateTime(), nullable=True))
        # Removed alter_column for odds.id - it's an identity column in PostgreSQL
        # and doesn't need to be changed from BIGINT to Integer
        try:
            op.alter_column('odds', 'home_team',
                       existing_type=sa.TEXT(),
                       type_=sa.String(length=100),
                       existing_nullable=False)
            op.alter_column('odds', 'away_team',
                       existing_type=sa.TEXT(),
                       type_=sa.String(length=100),
                       existing_nullable=False)
            op.alter_column('odds', 'result',
                       existing_type=sa.TEXT(),
                       type_=sa.String(length=10),
                       existing_nullable=True)
            op.alter_column('odds', 'country',
                       existing_type=sa.TEXT(),
                       type_=sa.String(length=50),
                       existing_nullable=True)
            op.alter_column('odds', 'league',
                       existing_type=sa.TEXT(),
                       type_=sa.String(length=100),
                       existing_nullable=False)
        except Exception:
            pass  # Columns might already be the correct type
        # Drop indexes if they exist
        try:
            op.drop_index('idx_odds_away_team_date', table_name='odds')
            op.drop_index('idx_odds_country_league', table_name='odds')
            op.drop_index('idx_odds_date', table_name='odds')
            op.drop_index('idx_odds_date_completed_only', table_name='odds', postgresql_where='(result IS NOT NULL)')
            op.drop_index('idx_odds_home_away', table_name='odds')
            op.drop_index('idx_odds_home_team_date', table_name='odds')
            op.drop_index('idx_odds_league_date', table_name='odds')
            op.drop_index('idx_odds_upcoming_by_league', table_name='odds', postgresql_where='(result IS NULL)')
            op.drop_constraint('odds_unique_match', 'odds', type_='unique')
        except Exception:
            pass  # Indexes/constraints might not exist
        op.create_index(op.f('ix_odds_id'), 'odds', ['id'], unique=False)
    
    # Modify user_crypto_balances if it exists
    if table_exists('user_crypto_balances'):
        op.create_index('idx_user_asset_balance', 'user_crypto_balances', ['user_id', 'asset'], unique=True)
        op.create_foreign_key(None, 'user_crypto_balances', 'users', ['user_id'], ['id'])
    
    # Modify users table (we just created it, so these should work)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'user_crypto_balances', type_='foreignkey')
    op.drop_index('idx_user_asset_balance', table_name='user_crypto_balances')
    op.drop_index(op.f('ix_odds_id'), table_name='odds')
    op.create_unique_constraint('odds_unique_match', 'odds', ['country', 'league', 'season', 'date', 'time', 'home_team', 'away_team'])
    op.create_index('idx_odds_upcoming_by_league', 'odds', ['league', 'date'], unique=False, postgresql_where='(result IS NULL)')
    op.create_index('idx_odds_league_date', 'odds', ['league', 'date'], unique=False)
    op.create_index('idx_odds_home_team_date', 'odds', ['home_team', 'date'], unique=False)
    op.create_index('idx_odds_home_away', 'odds', ['home_team', 'away_team'], unique=False)
    op.create_index('idx_odds_date_completed_only', 'odds', ['date'], unique=False, postgresql_where='(result IS NOT NULL)')
    op.create_index('idx_odds_date', 'odds', ['date'], unique=False)
    op.create_index('idx_odds_country_league', 'odds', ['country', 'league'], unique=False)
    op.create_index('idx_odds_away_team_date', 'odds', ['away_team', 'date'], unique=False)
    op.alter_column('odds', 'league',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('odds', 'country',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('odds', 'result',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('odds', 'away_team',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('odds', 'home_team',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('odds', 'id',
               existing_type=sa.Integer(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('odds', 'ai_prediction_timestamp')
    op.drop_column('odds', 'ai_model_version')
    op.drop_column('odds', 'ai_confidence_score')
    op.drop_column('odds', 'ai_prob_away')
    op.drop_column('odds', 'ai_prob_draw')
    op.drop_column('odds', 'ai_prob_home')
    op.drop_column('odds', 'ai_true_odd_2')
    op.drop_column('odds', 'ai_true_odd_X')
    op.drop_column('odds', 'ai_true_odd_1')
    op.drop_constraint(None, 'deposit_intents', type_='foreignkey')
    op.drop_index('idx_deposit_user_status', table_name='deposit_intents')
    op.drop_index('idx_deposit_tx_hash', table_name='deposit_intents')
    op.drop_index('idx_deposit_expires_at', table_name='deposit_intents')
    op.drop_constraint(None, 'crypto_transactions', type_='foreignkey')
    op.drop_index('idx_crypto_tx_withdrawal_intent', table_name='crypto_transactions')
    op.drop_index('idx_crypto_tx_status', table_name='crypto_transactions')
    op.drop_index('idx_crypto_tx_deposit_intent', table_name='crypto_transactions')
    op.drop_index('idx_crypto_tx_created_at', table_name='crypto_transactions')
    op.alter_column('crypto_transactions', 'deposit_intent_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('crypto_transactions', 'withdrawal_intent_id')
    op.create_foreign_key('fk_betting_records_match_id', 'betting_records', 'odds', ['match_id'], ['id'])
    op.create_table('captcha_challenges',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('challenge_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('challenge_question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('correct_answer', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='captcha_challenges_pkey')
    )
    op.create_index('ix_captcha_challenges_id', 'captcha_challenges', ['id'], unique=False)
    op.create_index('ix_captcha_challenges_challenge_id', 'captcha_challenges', ['challenge_id'], unique=True)
    op.create_table('captcha_responses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('challenge_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('attempted_answer', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('validated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='captcha_responses_pkey')
    )
    op.create_index('ix_captcha_responses_id', 'captcha_responses', ['id'], unique=False)
    op.drop_index(op.f('ix_withdrawal_intents_id'), table_name='withdrawal_intents')
    op.drop_index('idx_withdrawal_user_status', table_name='withdrawal_intents')
    op.drop_index('idx_withdrawal_tx_hash', table_name='withdrawal_intents')
    op.drop_index('idx_withdrawal_status', table_name='withdrawal_intents')
    op.drop_index('idx_withdrawal_created_at', table_name='withdrawal_intents')
    op.drop_table('withdrawal_intents')
    op.drop_index(op.f('ix_user_daily_limits_id'), table_name='user_daily_limits')
    op.drop_index('idx_user_date_limits', table_name='user_daily_limits')
    op.drop_index('idx_date_limits', table_name='user_daily_limits')
    op.drop_table('user_daily_limits')
    op.drop_index(op.f('ix_platform_wallets_id'), table_name='platform_wallets')
    op.drop_index('idx_wallet_hot_active', table_name='platform_wallets')
    op.drop_index('idx_wallet_asset_network', table_name='platform_wallets')
    op.drop_table('platform_wallets')
    # ### end Alembic commands ###
