"""Add withdrawal and limit models

Revision ID: b0fa1d8d6ada
Revises: 
Create Date: 2025-12-10 18:18:37.386421

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect


def table_exists(table_name):
    """Check if a table exists in the database"""
    try:
        bind = op.get_bind()
        inspector = inspect(bind)
        return table_name in inspector.get_table_names()
    except Exception:
        # If transaction is in failed state or any other error, assume table doesn't exist
        # This allows the migration to continue and create tables
        return False

# revision identifiers, used by Alembic.
revision = 'b0fa1d8d6ada'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if this is a fresh database (no alembic_version table means fresh DB)
    # For safety, always check if users table exists - if not, it's a fresh DB
    is_fresh_db = False
    try:
        is_fresh_db = not table_exists('users')
    except Exception:
        # If we can't check, assume it's a fresh DB to be safe
        is_fresh_db = True
    
    # Create users table first (required by foreign keys)
    # For fresh databases, always create. For existing, check first.
    if is_fresh_db or not table_exists('users'):
        op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('google_id', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('funds_usd', sa.Numeric(precision=15, scale=2), nullable=False, server_default='0.00'),
    sa.Column('referral_code_used', sa.String(length=50), nullable=True),
    sa.Column('referred_by_affiliate_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    try:
        op.create_index('ix_users_id', 'users', ['id'], unique=False)
    except Exception:
        pass
    try:
        op.create_index('ix_users_email', 'users', ['email'], unique=True)
    except Exception:
        pass
    try:
        op.create_index('ix_users_username', 'users', ['username'], unique=True)
    except Exception:
        pass
    try:
        op.create_index('ix_users_google_id', 'users', ['google_id'], unique=True)
    except Exception:
        pass
    try:
        op.create_index('ix_users_referral_code_used', 'users', ['referral_code_used'], unique=False)
    except Exception:
        pass
    try:
        op.create_index('ix_users_referred_by_affiliate_id', 'users', ['referred_by_affiliate_id'], unique=False)
    except Exception:
        pass
    
    op.create_table('platform_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset', sa.String(length=10), nullable=False),
    sa.Column('network', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('balance', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('is_hot_wallet', sa.Boolean(), nullable=True),
    sa.Column('min_balance_threshold', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('max_balance_threshold', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_multisig', sa.Boolean(), nullable=True),
    sa.Column('required_signatures', sa.Integer(), nullable=True),
    sa.Column('total_signatures', sa.Integer(), nullable=True),
    sa.Column('wallet_name', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_balance_check', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_index('idx_wallet_asset_network', 'platform_wallets', ['asset', 'network'], unique=False)
    op.create_index('idx_wallet_hot_active', 'platform_wallets', ['is_hot_wallet', 'is_active'], unique=False)
    try:
        op.create_index('ix_platform_wallets_id', 'platform_wallets', ['id'], unique=False)
    except Exception:
        pass
    op.create_table('user_daily_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('deposits_count', sa.Integer(), nullable=True),
    sa.Column('deposits_amount_usd', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('withdrawals_count', sa.Integer(), nullable=True),
    sa.Column('withdrawals_amount_usd', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('bets_count', sa.Integer(), nullable=True),
    sa.Column('bets_amount_usd', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_date_limits', 'user_daily_limits', ['date'], unique=False)
    op.create_index('idx_user_date_limits', 'user_daily_limits', ['user_id', 'date'], unique=True)
    try:
        op.create_index('ix_user_daily_limits_id', 'user_daily_limits', ['id'], unique=False)
    except Exception:
        pass
    op.create_table('withdrawal_intents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset', sa.String(length=10), nullable=False),
    sa.Column('network', sa.String(length=20), nullable=False),
    sa.Column('amount_crypto', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('to_address', sa.String(length=100), nullable=False),
    sa.Column('memo', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('tx_hash', sa.String(length=100), nullable=True),
    sa.Column('confirmations', sa.Integer(), nullable=True),
    sa.Column('network_fee', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('platform_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('kyc_required', sa.Boolean(), nullable=True),
    sa.Column('kyc_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_withdrawal_created_at', 'withdrawal_intents', ['created_at'], unique=False)
    op.create_index('idx_withdrawal_status', 'withdrawal_intents', ['status'], unique=False)
    op.create_index('idx_withdrawal_tx_hash', 'withdrawal_intents', ['tx_hash'], unique=False)
    op.create_index('idx_withdrawal_user_status', 'withdrawal_intents', ['user_id', 'status'], unique=False)
    try:
        op.create_index('ix_withdrawal_intents_id', 'withdrawal_intents', ['id'], unique=False)
    except Exception:
        pass
    
    # Create deposit_intents table if it doesn't exist
    # For fresh databases, always create. For existing, check first.
    if is_fresh_db or not table_exists('deposit_intents'):
        op.create_table('deposit_intents',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('asset', sa.String(length=10), nullable=False),
        sa.Column('network', sa.String(length=20), nullable=False),
        sa.Column('amount_quote_fiat', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('amount_crypto', sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column('generated_address', sa.String(length=100), nullable=False),
        sa.Column('memo', sa.String(length=100), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('tx_hash', sa.String(length=100), nullable=True),
        sa.Column('confirmations', sa.Integer(), nullable=True),
        sa.Column('required_confirmations', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('detected_at', sa.DateTime(), nullable=True),
        sa.Column('confirmed_at', sa.DateTime(), nullable=True),
        sa.Column('settled_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('idx_deposit_expires_at', 'deposit_intents', ['expires_at'], unique=False)
        op.create_index('idx_deposit_tx_hash', 'deposit_intents', ['tx_hash'], unique=False)
        op.create_index('idx_deposit_user_status', 'deposit_intents', ['user_id', 'status'], unique=False)
        try:
            op.create_index('ix_deposit_intents_id', 'deposit_intents', ['id'], unique=False)
        except Exception:
            pass
    
    # Create crypto_transactions table if it doesn't exist
    if is_fresh_db or not table_exists('crypto_transactions'):
        op.create_table('crypto_transactions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('deposit_intent_id', sa.Integer(), nullable=True),
        sa.Column('withdrawal_intent_id', sa.Integer(), nullable=True),
        sa.Column('tx_hash', sa.String(length=100), nullable=False),
        sa.Column('from_address', sa.String(length=100), nullable=True),
        sa.Column('to_address', sa.String(length=100), nullable=False),
        sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column('asset', sa.String(length=10), nullable=False),
        sa.Column('network', sa.String(length=20), nullable=False),
        sa.Column('block_number', sa.Integer(), nullable=True),
        sa.Column('confirmations', sa.Integer(), nullable=True),
        sa.Column('fee', sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['deposit_intent_id'], ['deposit_intents.id'], ),
        sa.ForeignKeyConstraint(['withdrawal_intent_id'], ['withdrawal_intents.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tx_hash')
        )
        op.create_index('idx_crypto_tx_created_at', 'crypto_transactions', ['created_at'], unique=False)
        op.create_index('idx_crypto_tx_deposit_intent', 'crypto_transactions', ['deposit_intent_id'], unique=False)
        op.create_index('idx_crypto_tx_status', 'crypto_transactions', ['status'], unique=False)
        op.create_index('idx_crypto_tx_withdrawal_intent', 'crypto_transactions', ['withdrawal_intent_id'], unique=False)
        try:
            op.create_index('ix_crypto_transactions_id', 'crypto_transactions', ['id'], unique=False)
        except Exception:
            pass
    
    # Create betting_records table if it doesn't exist
    if is_fresh_db or not table_exists('betting_records'):
        op.create_table('betting_records',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('bet_amount', sa.Float(), nullable=False),
        sa.Column('potential_win', sa.Float(), nullable=False),
        sa.Column('actual_profit', sa.Float(), nullable=True),
        sa.Column('match_id', sa.Integer(), nullable=True),
        sa.Column('match_teams', sa.String(length=255), nullable=False),
        sa.Column('match_date', sa.DateTime(), nullable=True),
        sa.Column('match_league', sa.String(length=100), nullable=True),
        sa.Column('match_status', sa.String(length=50), nullable=True),
        sa.Column('selected_outcome', sa.String(length=50), nullable=False),
        sa.Column('selected_team', sa.String(length=100), nullable=True),
        sa.Column('odds_value', sa.String(length=20), nullable=False),
        sa.Column('odds_decimal', sa.Float(), nullable=False),
        sa.Column('bet_status', sa.String(length=50), nullable=True),
        sa.Column('is_settled', sa.Boolean(), nullable=True),
        sa.Column('settlement_date', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        try:
            op.create_index('ix_betting_records_id', 'betting_records', ['id'], unique=False)
        except Exception:
            pass
    
    # Create odds table if it doesn't exist
    if is_fresh_db or not table_exists('odds'):
        op.create_table('odds',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('season', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('time', sa.Time(), nullable=True),
        sa.Column('home_team', sa.String(length=100), nullable=False),
        sa.Column('away_team', sa.String(length=100), nullable=False),
        sa.Column('result', sa.String(length=10), nullable=True),
        sa.Column('odd_1', sa.Numeric(), nullable=True),
        sa.Column('odd_X', sa.Numeric(), nullable=True),
        sa.Column('odd_2', sa.Numeric(), nullable=True),
        sa.Column('bets', sa.Integer(), nullable=True),
        sa.Column('country', sa.String(length=50), nullable=True),
        sa.Column('league', sa.String(length=100), nullable=False),
        sa.Column('pre_odd_1', sa.Numeric(), nullable=True),
        sa.Column('pre_odd_X', sa.Numeric(), nullable=True),
        sa.Column('pre_odd_2', sa.Numeric(), nullable=True),
        sa.Column('ai_true_odd_1', sa.Numeric(), nullable=True),
        sa.Column('ai_true_odd_X', sa.Numeric(), nullable=True),
        sa.Column('ai_true_odd_2', sa.Numeric(), nullable=True),
        sa.Column('ai_prob_home', sa.Float(), nullable=True),
        sa.Column('ai_prob_draw', sa.Float(), nullable=True),
        sa.Column('ai_prob_away', sa.Float(), nullable=True),
        sa.Column('ai_confidence_score', sa.Float(), nullable=True),
        sa.Column('ai_model_version', sa.String(length=255), nullable=True),
        sa.Column('ai_prediction_timestamp', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_odds_id'), 'odds', ['id'], unique=False)
    
    # Create user_crypto_balances table if it doesn't exist
    if is_fresh_db or not table_exists('user_crypto_balances'):
        op.create_table('user_crypto_balances',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('asset', sa.String(length=10), nullable=False),
        sa.Column('balance', sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column('locked_balance', sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('idx_user_asset_balance', 'user_crypto_balances', ['user_id', 'asset'], unique=True)
        try:
            op.create_index('ix_user_crypto_balances_id', 'user_crypto_balances', ['id'], unique=False)
        except Exception:
            pass
    
    # Create crypto_inventory table if it doesn't exist
    if is_fresh_db or not table_exists('crypto_inventory'):
        op.create_table('crypto_inventory',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('asset', sa.String(length=10), nullable=False),
        sa.Column('network', sa.String(length=20), nullable=False),
        sa.Column('address', sa.String(length=100), nullable=False),
        sa.Column('private_key_encrypted', sa.Text(), nullable=True),
        sa.Column('balance', sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        try:
            op.create_index('ix_crypto_inventory_id', 'crypto_inventory', ['id'], unique=False)
        except Exception:
            pass
    
    # Drop captcha tables if they exist (legacy tables)
    if table_exists('captcha_responses'):
        op.drop_index('ix_captcha_responses_id', table_name='captcha_responses')
        op.drop_table('captcha_responses')
    if table_exists('captcha_challenges'):
        op.drop_index('ix_captcha_challenges_challenge_id', table_name='captcha_challenges')
        op.drop_index('ix_captcha_challenges_id', table_name='captcha_challenges')
        op.drop_table('captcha_challenges')
    
    # Modify betting_records if it exists (and wasn't just created)
    if table_exists('betting_records'):
        bind = op.get_bind()
        inspector = inspect(bind)
        try:
            foreign_keys = [fk['name'] for fk in inspector.get_foreign_keys('betting_records')]
        except Exception:
            foreign_keys = []
        
        # Drop old foreign key constraint if it exists (legacy constraint)
        if any('fk_betting_records_match_id' in str(fk) for fk in foreign_keys):
            try:
                op.drop_constraint('fk_betting_records_match_id', 'betting_records', type_='foreignkey')
            except Exception:
                pass  # Constraint might not exist
    
    # Modify crypto_transactions if it exists (and wasn't just created)
    # Check if withdrawal_intent_id column exists to determine if table needs modification
    if table_exists('crypto_transactions'):
        bind = op.get_bind()
        inspector = inspect(bind)
        try:
            columns = [col['name'] for col in inspector.get_columns('crypto_transactions')]
        except Exception:
            columns = []
        
        if 'withdrawal_intent_id' not in columns:
            op.add_column('crypto_transactions', sa.Column('withdrawal_intent_id', sa.Integer(), nullable=True))
        try:
            op.alter_column('crypto_transactions', 'deposit_intent_id',
                       existing_type=sa.INTEGER(),
                       nullable=True)
        except Exception:
            pass  # Column might already be nullable
        
        # Only create indexes if they don't exist
        try:
            indexes = [idx['name'] for idx in inspector.get_indexes('crypto_transactions')]
        except Exception:
            indexes = []
        if 'idx_crypto_tx_created_at' not in indexes:
            op.create_index('idx_crypto_tx_created_at', 'crypto_transactions', ['created_at'], unique=False)
        if 'idx_crypto_tx_deposit_intent' not in indexes:
            op.create_index('idx_crypto_tx_deposit_intent', 'crypto_transactions', ['deposit_intent_id'], unique=False)
        if 'idx_crypto_tx_status' not in indexes:
            op.create_index('idx_crypto_tx_status', 'crypto_transactions', ['status'], unique=False)
        if 'idx_crypto_tx_withdrawal_intent' not in indexes:
            op.create_index('idx_crypto_tx_withdrawal_intent', 'crypto_transactions', ['withdrawal_intent_id'], unique=False)
        
        # Only add foreign key if it doesn't exist
        try:
            foreign_keys = [fk['name'] for fk in inspector.get_foreign_keys('crypto_transactions')]
        except Exception:
            foreign_keys = []
        withdrawal_fk_exists = any('withdrawal_intent_id' in str(fk) for fk in foreign_keys)
        if not withdrawal_fk_exists and 'withdrawal_intent_id' in columns:
            try:
                op.create_foreign_key(None, 'crypto_transactions', 'withdrawal_intents', ['withdrawal_intent_id'], ['id'])
            except Exception:
                pass  # Foreign key might already exist
    
    # Modify deposit_intents if it exists (and wasn't just created)
    if table_exists('deposit_intents'):
        bind = op.get_bind()
        inspector = inspect(bind)
        try:
            indexes = [idx['name'] for idx in inspector.get_indexes('deposit_intents')]
            foreign_keys = [fk['name'] for fk in inspector.get_foreign_keys('deposit_intents')]
        except Exception:
            indexes = []
            foreign_keys = []
        
        # Only create indexes if they don't exist
        if 'idx_deposit_expires_at' not in indexes:
            try:
                op.create_index('idx_deposit_expires_at', 'deposit_intents', ['expires_at'], unique=False)
            except Exception:
                pass
        if 'idx_deposit_tx_hash' not in indexes:
            try:
                op.create_index('idx_deposit_tx_hash', 'deposit_intents', ['tx_hash'], unique=False)
            except Exception:
                pass
        if 'idx_deposit_user_status' not in indexes:
            try:
                op.create_index('idx_deposit_user_status', 'deposit_intents', ['user_id', 'status'], unique=False)
            except Exception:
                pass
        
        # Only add foreign key if it doesn't exist
        user_fk_exists = any('user_id' in str(fk) for fk in foreign_keys)
        if not user_fk_exists:
            try:
                op.create_foreign_key(None, 'deposit_intents', 'users', ['user_id'], ['id'])
            except Exception:
                pass  # Foreign key might already exist
    
    # Modify odds if it exists (and wasn't just created)
    if table_exists('odds'):
        bind = op.get_bind()
        inspector = inspect(bind)
        try:
            columns = [col['name'] for col in inspector.get_columns('odds')]
        except Exception:
            # Transaction might be in failed state, skip modification
            columns = []
        
        # Only add columns if they don't exist
        if 'ai_true_odd_X' not in columns:
            try:
                op.add_column('odds', sa.Column('ai_true_odd_X', sa.Numeric(), nullable=True))
            except Exception:
                pass
        if 'ai_true_odd_2' not in columns:
            try:
                op.add_column('odds', sa.Column('ai_true_odd_2', sa.Numeric(), nullable=True))
            except Exception:
                pass
        if 'ai_prob_home' not in columns:
            try:
                op.add_column('odds', sa.Column('ai_prob_home', sa.Float(), nullable=True))
            except Exception:
                pass
        if 'ai_prob_draw' not in columns:
            try:
                op.add_column('odds', sa.Column('ai_prob_draw', sa.Float(), nullable=True))
            except Exception:
                pass
        if 'ai_prob_away' not in columns:
            try:
                op.add_column('odds', sa.Column('ai_prob_away', sa.Float(), nullable=True))
            except Exception:
                pass
        if 'ai_confidence_score' not in columns:
            try:
                op.add_column('odds', sa.Column('ai_confidence_score', sa.Float(), nullable=True))
            except Exception:
                pass
        if 'ai_model_version' not in columns:
            try:
                op.add_column('odds', sa.Column('ai_model_version', sa.String(length=255), nullable=True))
            except Exception:
                pass
        if 'ai_prediction_timestamp' not in columns:
            try:
                op.add_column('odds', sa.Column('ai_prediction_timestamp', sa.DateTime(), nullable=True))
            except Exception:
                pass
        # Removed alter_column for odds.id - it's an identity column in PostgreSQL
        # and doesn't need to be changed from BIGINT to Integer
        try:
            op.alter_column('odds', 'home_team',
                       existing_type=sa.TEXT(),
                       type_=sa.String(length=100),
                       existing_nullable=False)
            op.alter_column('odds', 'away_team',
                       existing_type=sa.TEXT(),
                       type_=sa.String(length=100),
                       existing_nullable=False)
            op.alter_column('odds', 'result',
                       existing_type=sa.TEXT(),
                       type_=sa.String(length=10),
                       existing_nullable=True)
            op.alter_column('odds', 'country',
                       existing_type=sa.TEXT(),
                       type_=sa.String(length=50),
                       existing_nullable=True)
            op.alter_column('odds', 'league',
                       existing_type=sa.TEXT(),
                       type_=sa.String(length=100),
                       existing_nullable=False)
        except Exception:
            pass  # Columns might already be the correct type
        # Drop indexes if they exist (use raw SQL with IF EXISTS to avoid transaction abort)
        bind = op.get_bind()
        indexes_to_drop = [
            'idx_odds_away_team_date',
            'idx_odds_country_league',
            'idx_odds_date',
            'idx_odds_home_away',
            'idx_odds_home_team_date',
            'idx_odds_league_date',
        ]
        for idx_name in indexes_to_drop:
            try:
                op.execute(f'DROP INDEX IF EXISTS {idx_name};')
            except Exception:
                pass
        
        # Drop partial indexes (with WHERE clause)
        try:
            op.execute('DROP INDEX IF EXISTS idx_odds_date_completed_only;')
        except Exception:
            pass
        try:
            op.execute('DROP INDEX IF EXISTS idx_odds_upcoming_by_league;')
        except Exception:
            pass
        
        # Drop unique constraint if exists
        try:
            op.execute('ALTER TABLE odds DROP CONSTRAINT IF EXISTS odds_unique_match;')
        except Exception:
            pass
        
        # Only create index if it doesn't exist
        try:
            indexes = [idx['name'] for idx in inspector.get_indexes('odds')]
        except Exception:
            # Transaction might be in failed state, assume index doesn't exist
            indexes = []
        if 'ix_odds_id' not in indexes:
            try:
                try:
                    op.create_index('ix_odds_id', 'odds', ['id'], unique=False)
                except Exception:
                    pass
            except Exception:
                pass
    
    # Modify user_crypto_balances if it exists (and wasn't just created)
    if table_exists('user_crypto_balances'):
        bind = op.get_bind()
        inspector = inspect(bind)
        try:
            indexes = [idx['name'] for idx in inspector.get_indexes('user_crypto_balances')]
            foreign_keys = [fk['name'] for fk in inspector.get_foreign_keys('user_crypto_balances')]
        except Exception:
            indexes = []
            foreign_keys = []
        
        # Only create index if it doesn't exist
        if 'idx_user_asset_balance' not in indexes:
            try:
                op.create_index('idx_user_asset_balance', 'user_crypto_balances', ['user_id', 'asset'], unique=True)
            except Exception:
                pass
        
        # Only add foreign key if it doesn't exist
        user_fk_exists = any('user_id' in str(fk) for fk in foreign_keys)
        if not user_fk_exists:
            try:
                op.create_foreign_key(None, 'user_crypto_balances', 'users', ['user_id'], ['id'])
            except Exception:
                pass  # Foreign key might already exist
    
    # Modify users table (only if it exists and wasn't just created)
    # For fresh databases, the table is already created with correct column types
    if not is_fresh_db and table_exists('users'):
        try:
            op.alter_column('users', 'created_at',
                       existing_type=postgresql.TIMESTAMP(timezone=True),
                       nullable=True,
                       existing_server_default=sa.text('now()'))
        except Exception:
            pass  # Column might already be in correct state
        try:
            op.alter_column('users', 'updated_at',
                       existing_type=postgresql.TIMESTAMP(timezone=True),
                       nullable=True,
                       existing_server_default=sa.text('now()'))
        except Exception:
            pass  # Column might already be in correct state
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'user_crypto_balances', type_='foreignkey')
    op.drop_index('idx_user_asset_balance', table_name='user_crypto_balances')
    op.drop_index('ix_odds_id', table_name='odds')
    op.create_unique_constraint('odds_unique_match', 'odds', ['country', 'league', 'season', 'date', 'time', 'home_team', 'away_team'])
    op.create_index('idx_odds_upcoming_by_league', 'odds', ['league', 'date'], unique=False, postgresql_where='(result IS NULL)')
    op.create_index('idx_odds_league_date', 'odds', ['league', 'date'], unique=False)
    op.create_index('idx_odds_home_team_date', 'odds', ['home_team', 'date'], unique=False)
    op.create_index('idx_odds_home_away', 'odds', ['home_team', 'away_team'], unique=False)
    op.create_index('idx_odds_date_completed_only', 'odds', ['date'], unique=False, postgresql_where='(result IS NOT NULL)')
    op.create_index('idx_odds_date', 'odds', ['date'], unique=False)
    op.create_index('idx_odds_country_league', 'odds', ['country', 'league'], unique=False)
    op.create_index('idx_odds_away_team_date', 'odds', ['away_team', 'date'], unique=False)
    op.alter_column('odds', 'league',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('odds', 'country',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('odds', 'result',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('odds', 'away_team',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('odds', 'home_team',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('odds', 'id',
               existing_type=sa.Integer(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('odds', 'ai_prediction_timestamp')
    op.drop_column('odds', 'ai_model_version')
    op.drop_column('odds', 'ai_confidence_score')
    op.drop_column('odds', 'ai_prob_away')
    op.drop_column('odds', 'ai_prob_draw')
    op.drop_column('odds', 'ai_prob_home')
    op.drop_column('odds', 'ai_true_odd_2')
    op.drop_column('odds', 'ai_true_odd_X')
    op.drop_column('odds', 'ai_true_odd_1')
    op.drop_constraint(None, 'deposit_intents', type_='foreignkey')
    op.drop_index('idx_deposit_user_status', table_name='deposit_intents')
    op.drop_index('idx_deposit_tx_hash', table_name='deposit_intents')
    op.drop_index('idx_deposit_expires_at', table_name='deposit_intents')
    op.drop_constraint(None, 'crypto_transactions', type_='foreignkey')
    op.drop_index('idx_crypto_tx_withdrawal_intent', table_name='crypto_transactions')
    op.drop_index('idx_crypto_tx_status', table_name='crypto_transactions')
    op.drop_index('idx_crypto_tx_deposit_intent', table_name='crypto_transactions')
    op.drop_index('idx_crypto_tx_created_at', table_name='crypto_transactions')
    op.alter_column('crypto_transactions', 'deposit_intent_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('crypto_transactions', 'withdrawal_intent_id')
    op.create_foreign_key('fk_betting_records_match_id', 'betting_records', 'odds', ['match_id'], ['id'])
    op.create_table('captcha_challenges',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('challenge_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('challenge_question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('correct_answer', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_attempts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='captcha_challenges_pkey')
    )
    op.create_index('ix_captcha_challenges_id', 'captcha_challenges', ['id'], unique=False)
    op.create_index('ix_captcha_challenges_challenge_id', 'captcha_challenges', ['challenge_id'], unique=True)
    op.create_table('captcha_responses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('challenge_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('attempted_answer', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('validated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='captcha_responses_pkey')
    )
    op.create_index('ix_captcha_responses_id', 'captcha_responses', ['id'], unique=False)
    op.drop_index('ix_withdrawal_intents_id', table_name='withdrawal_intents')
    op.drop_index('idx_withdrawal_user_status', table_name='withdrawal_intents')
    op.drop_index('idx_withdrawal_tx_hash', table_name='withdrawal_intents')
    op.drop_index('idx_withdrawal_status', table_name='withdrawal_intents')
    op.drop_index('idx_withdrawal_created_at', table_name='withdrawal_intents')
    op.drop_table('withdrawal_intents')
    op.drop_index('ix_user_daily_limits_id', table_name='user_daily_limits')
    op.drop_index('idx_user_date_limits', table_name='user_daily_limits')
    op.drop_index('idx_date_limits', table_name='user_daily_limits')
    op.drop_table('user_daily_limits')
    op.drop_index('ix_platform_wallets_id', table_name='platform_wallets')
    op.drop_index('idx_wallet_hot_active', table_name='platform_wallets')
    op.drop_index('idx_wallet_asset_network', table_name='platform_wallets')
    op.drop_table('platform_wallets')
    # ### end Alembic commands ###
