"""add_wallet_transactions_table

Revision ID: b59a7b46e2df
Revises: b0fa1d8d6ada
Create Date: 2025-12-15 22:20:16.957649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b59a7b46e2df'
down_revision = 'b0fa1d8d6ada'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset', sa.String(length=10), nullable=False),
    sa.Column('type', sa.Enum('DEPOSIT_CREDIT', 'BET_LOCK', 'BET_UNLOCK', 'BET_WIN', 'BET_LOSS', 'WITHDRAWAL_LOCK', 'WITHDRAWAL_UNLOCK', 'WITHDRAWAL_DEBIT', 'MANUAL_ADJUSTMENT', name='wallettransactiontype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('balance_before', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('reserved_before', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('reserved_after', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('reference_type', sa.Enum('DEPOSIT', 'BET', 'WITHDRAWAL', 'MANUAL', name='referencetype'), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('metadata_json', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wallet_tx_reference', 'wallet_transactions', ['reference_type', 'reference_id'], unique=False)
    op.create_index('idx_wallet_tx_type_date', 'wallet_transactions', ['type', 'created_at'], unique=False)
    op.create_index('idx_wallet_tx_user_asset', 'wallet_transactions', ['user_id', 'asset'], unique=False)
    op.create_index('idx_wallet_tx_user_date', 'wallet_transactions', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_asset'), 'wallet_transactions', ['asset'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_created_at'), 'wallet_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_id'), 'wallet_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_type'), 'wallet_transactions', ['type'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_user_id'), 'wallet_transactions', ['user_id'], unique=False)
    # Removed alter_column for odds.id - it's an identity column in PostgreSQL
    # and doesn't need to be changed from BIGINT to Integer
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed alter_column for odds.id - it's an identity column in PostgreSQL
    op.drop_index(op.f('ix_wallet_transactions_user_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_type'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_created_at'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_asset'), table_name='wallet_transactions')
    op.drop_index('idx_wallet_tx_user_date', table_name='wallet_transactions')
    op.drop_index('idx_wallet_tx_user_asset', table_name='wallet_transactions')
    op.drop_index('idx_wallet_tx_type_date', table_name='wallet_transactions')
    op.drop_index('idx_wallet_tx_reference', table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    # ### end Alembic commands ###
